// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/orta": {
    params: {};
  };
  "/orta/byby": {
    params: {};
  };
  "/orta/*": {
    params: {
      "*": string;
    };
  };
  "/byby": {
    params: {};
  };
  "/byby/user/:username?": {
    params: {
      "username"?: string;
    };
  };
  "/nested": {
    params: {};
  };
  "/nested/nested1": {
    params: {};
  };
  "/nested/nested2": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/auth/login" | "/auth/register" | "/orta" | "/orta/byby" | "/orta/*" | "/byby" | "/byby/user/:username?" | "/nested" | "/nested/nested1" | "/nested/nested2";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./auth/layout.tsx": {
    id: "auth/layout";
    page: "/auth" | "/auth/login" | "/auth/register";
  };
  "./auth/index.tsx": {
    id: "auth/index";
    page: "/auth";
  };
  "./auth/login.tsx": {
    id: "auth/login";
    page: "/auth/login";
  };
  "./auth/register.tsx": {
    id: "auth/register";
    page: "/auth/register";
  };
  "./orta/layout.tsx": {
    id: "orta/layout";
    page: "/orta" | "/orta/byby";
  };
  "./orta/orta.tsx": {
    id: "orta/orta";
    page: "/orta";
  };
  "./orta/ortabyby.tsx": {
    id: "orta/ortabyby";
    page: "/orta/byby";
  };
  "./orta/orta.catchall.tsx": {
    id: "orta/orta.catchall";
    page: "/orta/*";
  };
  "./byby/byby.tsx": {
    id: "byby/byby";
    page: "/byby";
  };
  "./byby/user.tsx": {
    id: "byby/user";
    page: "/byby/user/:username?";
  };
  "./nested/nested.tsx": {
    id: "nested/nested";
    page: "/nested" | "/nested/nested1" | "/nested/nested2";
  };
  "./nested/nested1/nested1.tsx": {
    id: "nested/nested1/nested1";
    page: "/nested/nested1";
  };
  "./nested/nested2/nested2.tsx": {
    id: "nested/nested2/nested2";
    page: "/nested/nested2";
  };
};